name: Heroku Deploy
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      HEROKU_API_KEY:
        required: true
      HEROKU_APP_NAME:
        required: true
      HEROKU_EMAIL:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Set git config
        run: |
          git config --global user.name "heroku-deploy"
          git config --global user.email $HEROKU_EMAIL
      - name: Add Heroku remote
        run: git remote add heroku git@heroku.com:$HEROKU_APP_NAME.git
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Push to Heroku
        run: git push heroku ${{ inputs.branch }}:master --force
