name: Pull Request
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13'
      - name: Download dependencies
        run: npm ci
      - name: Run typecheck
        run: npm run typecheck
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm test
